=== almangad/TrabajoSD_Alba_Mangado/xlm/Reyes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Reyes (regente|pretendiente)*>
<!ELEMENT regente (nombreCompleto, apodo, curiosidad+, nacimiento, LaRioja?, BajaNavarra?, Francia?, Aragon?, Castilla?, Leon?)>
<!ELEMENT pretendiente (nombreCompleto, pretension, curiosidad+, nacimiento)>

<!ELEMENT nombreCompleto (#PCDATA)>
<!ELEMENT apodo (#PCDATA)>
<!ELEMENT curiosidad (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT LaRioja EMPTY>
<!ELEMENT BajaNavarra EMPTY>
<!ELEMENT Francia EMPTY>
<!ELEMENT Aragon EMPTY>
<!ELEMENT Castilla EMPTY>
<!ELEMENT Leon EMPTY>
<!ELEMENT pretension (#PCDATA)>

<!ATTLIST Reyes 
	nombreOficial CDATA #REQUIRED
>
<!ATTLIST regente 
	genero (rey|reina) #REQUIRED
	inicioReinado CDATA #IMPLIED
	finReinado CDATA #IMPLIED
	dinastia (Arista|Jimena|Champaña|Capeta|Évreux|Trastamara|Foix|Albret|Borbon|Austria|Saboya|Bonaparte) #REQUIRED
>
<!ATTLIST pretendiente 
	genero (rey|reina) #REQUIRED
	dinastia (Arista|Jimena|Champaña|Capeta|Évreux|Trastamara|Foix|Albret|Borbon|Austria|Saboya|Bonaparte) #REQUIRED
>

=== almangad/TrabajoSD_Alba_Mangado/ReinoNavarra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Reyes SYSTEM "C:\Users\Alba Mangado\IdeaProjects\TrabajoSD_Alba_Mangado\Reyes.dtd">
<Reyes nombreOficial="Reino de Pamplona o Navarra">
	<regente genero="rey" dinastia="Arista" finReinado="851">
		<nombreCompleto>Íñigo Arista</nombreCompleto>
		<apodo>El vascón</apodo>
		<curiosidad>Participó en la batalla de Roncesvalles</curiosidad>
		<nacimiento>790, Condado de Bigorra</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Arista" inicioReinado="851" finReinado="882">
		<nombreCompleto>García Íñiguez</nombreCompleto>
		<apodo>El pamplonés</apodo>
		<curiosidad>Fue prisionero de los vikingos</curiosidad>
		<nacimiento>810, Pamplona</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Arista" inicioReinado="882" finReinado="905">
		<nombreCompleto>Fortún Garcés</nombreCompleto>
		<apodo>El monje</apodo>
		<curiosidad>Fue destronado y recluido al monasterio de Leyre</curiosidad>	
		<curiosidad>Estuvo cautivo en Córdoba</curiosidad>
		<curiosidad>Su hija se convirtión en la abueda de Abderramán III</curiosidad>
		<nacimiento>825, Pamplona</nacimiento>
		<Aragon/>
	</regente>
	<pretendiente genero="reina" dinastia="Arista">
		<nombreCompleto>Toda Aznarez</nombreCompleto>
		<pretension>Fue nombrada la heredera de su abuelo para que su marido (Sancho Garcés) ascendiera al trono</pretension>
		<curiosidad>Se consiguió que su sobrino, Abderramán III, no atacase Navarra y, posteriormente, devolviese a su nieto al trono de León</curiosidad>
		<nacimiento>2-1-876, Castillo de Larraun</nacimiento>
	</pretendiente>
	
	<regente genero="rey" dinastia="Jimena" inicioReinado="905" finReinado="925">
		<nombreCompleto>Sancho Garcés I</nombreCompleto>
		<apodo>El Primer Rey</apodo>
		<curiosidad>Murión al salir a galope su caballo, y su sepultura se estableción en San Esteban, de Deyo (Monjardín) o de Resa, pues recientemente se ha abierto el debate.</curiosidad>	
		<nacimiento>887, Rocaforte</nacimiento>
		<LaRioja/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="925" finReinado="970">
		<nombreCompleto>García Sanchez I</nombreCompleto>
		<apodo>El de la batalla de Simancas</apodo>
		<curiosidad>Acendió al trono con 6 años, por lo que, hasta los 15 hubo regencias de su tío y su madre</curiosidad>	
		<nacimiento>919, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="970" finReinado="994">
		<nombreCompleto>Sancho garcés II</nombreCompleto>
		<apodo>Abarca</apodo>
		<curiosidad>Realizó una visita pacífica a Almanzor, en Córdoba, donde conoció a su nieto Abderramán "Sanchuelo"</curiosidad>	
		<nacimiento>938, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="994" finReinado="1000">
		<nombreCompleto>García Sanchez II</nombreCompleto>
		<apodo>El Temblón</apodo>
		<curiosidad>Tras su muerte no hubo rey por 4 años</curiosidad>	
		<nacimiento>964, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1004" finReinado="1035">
		<nombreCompleto>Sancho garcés III</nombreCompleto>
		<apodo>El Mayor</apodo>
		<curiosidad>Tras tomar León se proclamó "Imperator Totius Hispaniae"</curiosidad>		
		<curiosidad>Tras su muerte repartió todos sus territorios entre sus hijos, pasando Aragón y Castilla de condados a reinos</curiosidad>	
		<nacimiento>990, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
		<Castilla/>
		<Leon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1035" finReinado="1054">
		<nombreCompleto>García Sanchez III</nombreCompleto>
		<apodo>El de Nájera</apodo>
		<curiosidad>Intentó mover la tumba de San Millán a Nájera, pero los bueyes se pararon en seco en donde se construiría el monasterio de San Millán de Yuso</curiosidad>	
		<nacimiento>1012, Nájera</nacimiento>
		<LaRioja/>
		<Castilla/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1054" finReinado="1076">
		<nombreCompleto>Sancho V garcés</nombreCompleto>
		<apodo>El de Peñalén</apodo>
		<curiosidad>Murió al empujarlo sus hermanos por el barraco de Peñalén</curiosidad>		
		<nacimiento>1039, Nájera</nacimiento>
		<LaRioja/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1076" finReinado="1094" >
		<nombreCompleto>Sancho V Ramírez</nombreCompleto>
		<apodo>Sancho de Aragón</apodo>
		<curiosidad>Como los navarros no querían un rey asesino, lo nombraron en vez de su primo</curiosidad>
		<nacimiento>c. 1042</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" inicioReinado="1094" finReinado="1104" dinastia="Jimena">
		<nombreCompleto>Pedro I</nombreCompleto>
		<apodo>Pedro de Aragón</apodo>
		<curiosidad>Hijo de Sancho V, continuó la unión de coronas.</curiosidad>
		<nacimiento>c. 1068</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" inicioReinado="1104" finReinado="1134" dinastia="Jimena">
		<nombreCompleto>Alfonso I</nombreCompleto>
		<apodo>el Batallador</apodo>
		<curiosidad>Murió sin descendencia, lo que provocó la separación de los reinos</curiosidad>
		<curiosidad>Maltrataba a su mujer, Urraca de León</curiosidad>
		<nacimiento>c. 1073</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" inicioReinado="1134" finReinado="1150" dinastia="Jimena">
		<nombreCompleto>García V Ramírez</nombreCompleto>
		<apodo>el Restaurador</apodo>
		<curiosidad>Nieto bastardo del rey Sancho el mayor y del cid</curiosidad>
		<nacimiento>Desconocido</nacimiento>
	</regente>
	<regente genero="rey" inicioReinado="1150" finReinado="1194" dinastia="Jimena">
		<nombreCompleto>Sancho VI</nombreCompleto>
		<apodo>el Sabio</apodo>
		<curiosidad>Fue el primero en utilizar oficialmente el título de "Rey de Navarra".</curiosidad>
		<nacimiento>c. 1132</nacimiento>
	</regente>
	<regente genero="rey" inicioReinado="1194" finReinado="1234" dinastia="Jimena">
		<nombreCompleto>Sancho VII</nombreCompleto>
		<apodo>el Fuerte</apodo>
		<curiosidad>Participó en la Batalla de las Navas de Tolosa y, según la leyenda, se llevó las cadenas del emir almohade como trofeo.</curiosidad>
		<nacimiento>c. 1157</nacimiento>
	</regente>
</Reyes>

=== almangad/TrabajoSD_Alba_Mangado/xlm/ReinoNavarra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Reyes SYSTEM "Reyes.dtd">
<Reyes nombreOficial="Reino de Pamplona o Navarra">
	<regente genero="rey" dinastia="Arista" finReinado="851">
		<nombreCompleto>Íñigo Arista</nombreCompleto>
		<apodo>El vascón</apodo>
		<curiosidad>Participó en la batalla de Roncesvalles</curiosidad>
		<nacimiento>790, Condado de Bigorra</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Arista" inicioReinado="851" finReinado="882">
		<nombreCompleto>Garcá Íñiguez</nombreCompleto>
		<apodo>El pamplonés</apodo>
		<curiosidad>Fue prisionero de los vikingos</curiosidad>
		<nacimiento>810, Pamplona</nacimiento>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Arista" inicioReinado="882" finReinado="905">
		<nombreCompleto>Fortún Garcés</nombreCompleto>
		<apodo>El monje</apodo>
		<curiosidad>Fue destronado y recluido al monasterio de Leyre</curiosidad>	
		<curiosidad>Estuvo cautivo en Córdoba</curiosidad>
		<curiosidad>Su hija se convirtión en la abueda de Abderramán III</curiosidad>
		<nacimiento>825, Pamplona</nacimiento>
		<Aragon/>
	</regente>
	<pretendiente genero="reina" dinastia="Arista">
		<nombreCompleto>Toda Aznarez</nombreCompleto>
		<pretension>Fue nombrada la heredera de su abuelo para que su marido (Sancho Garcés) ascendiera al trono</pretension>
		<curiosidad>Se consiguió que su sobrino, Abderramán III, no atacase Navarra y, posteriormente, devolviese a su nieto al trono de León</curiosidad>
		<nacimiento>2-1-876, Castillo de Larraun</nacimiento>
	</pretendiente>
	
	<regente genero="rey" dinastia="Jimena" inicioReinado="905" finReinado="925">
		<nombreCompleto>Sancho Garcés I</nombreCompleto>
		<apodo>El Primer Rey</apodo>
		<curiosidad>Murión al salir a galope su caballo, y su sepultura se estableción en San Esteban, de Deyo (Monjardín) o de Resa, pues recientemente se ha abierto el debate.</curiosidad>	
		<nacimiento>887, Rocaforte</nacimiento>
		<LaRioja/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="925" finReinado="970">
		<nombreCompleto>García Sanchez I</nombreCompleto>
		<apodo>El de la batalla de Simancas</apodo>
		<curiosidad>Acendió al trono con 6 años, por lo que, hasta los 15 hubo regencias de su tío y su madre</curiosidad>	
		<nacimiento>919, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="970" finReinado="994">
		<nombreCompleto>Sancho garcés II</nombreCompleto>
		<apodo>Abarca</apodo>
		<curiosidad>Realizó una visita pacífica a Almanzor, en Córdoba, donde conoció a su nieto Abderramán "Sanchuelo"</curiosidad>	
		<nacimiento>938, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="994" finReinado="1000">
		<nombreCompleto>García Sanchez II</nombreCompleto>
		<apodo>El Temblón</apodo>
		<curiosidad>Tras su muerte no hubo rey por 4 años</curiosidad>	
		<nacimiento>964, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1004" finReinado="1035">
		<nombreCompleto>Sancho garcés III</nombreCompleto>
		<apodo>El Mayor</apodo>
		<curiosidad>Tras tomar León se proclamó "Imperator Totius Hispaniae"</curiosidad>		
		<curiosidad>Tras su muerte repartió todos sus territorios entre sus hijos, pasando Aragón y Castilla de condados a reinos</curiosidad>	
		<nacimiento>990, Pamplona</nacimiento>
		<LaRioja/>
		<Aragon/>
		<Castilla/>
		<Leon/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1035" finReinado="1054">
		<nombreCompleto>García Sanchez III</nombreCompleto>
		<apodo>El de Nájera</apodo>
		<curiosidad>Intentó mover la tumba de San Millán a Nájera, pero los bueyes se pararon en seco en donde se construiría el monasterio de San Millán de Yuso</curiosidad>	
		<nacimiento>1012, Nájera</nacimiento>
		<LaRioja/>
		<Castilla/>
	</regente>
	<regente genero="rey" dinastia="Jimena" inicioReinado="1054" finReinado="1076">
		<nombreCompleto>Sancho garcés III</nombreCompleto>
		<apodo>El de Peñalén</apodo>
		<curiosidad>Murió al empujarlo sus hermanos por el barraco de Peñalén</curiosidad>		
		<nacimiento>1039, Nájera</nacimiento>
		<LaRioja/>
	</regente>
</Reyes>
